const api = {
  items: [
    {
      id: 1,
      name: 'Alayna Bronder',
      age: 20,
      eligible: true,
    },
    {
      id: 2,
      name: 'Sharita Burfield',
      age: 31,
      eligible: true,
    },
    {
      id: 3,
      name: 'Jeanna Such',
      age: 49,
      eligible: false,
    },
    {
      id: 4,
      name: 'Maura Heishman',
      age: 67,
      eligible: true,
    },
    {
      id: 5,
      name: 'Caitlyn Sierra',
      age: 22,
      eligible: false,
    },
    {
      id: 6,
      name: 'Charita Woodford',
      age: 37,
      eligible: true,
    },
    {
      id: 7,
      name: 'Mitchel Donoghue',
      age: 35,
      eligible: false,
    },
    {
      id: 8,
      name: 'Ernestine Farfan',
      age: 19,
      eligible: false,
    },
    {
      id: 9,
      name: 'Cyndy Coffey',
      age: 51,
      eligible: true,
    },
    {
      id: 10,
      name: 'Rudolph Crean',
      age: 43,
      eligible: true,
    },
    {
      id: 11,
      name: 'Enola Kaczorowski',
      age: 18,
      eligible: false,
    },
    {
      id: 12,
      name: 'Maribeth Clewis',
      age: 62,
      eligible: true,
    },
    {
      id: 13,
      name: 'Andria Buscemi',
      age: 20,
      eligible: false,
    },
    {
      id: 14,
      name: 'Dianna Brewer',
      age: 21,
      eligible: false,
    },
    {
      id: 15,
      name: 'Todd Charette',
      age: 27,
      eligible: false,
    },
    {
      id: 16,
      name: 'Maryalice Cartier',
      age: 44,
      eligible: true,
    },
    {
      id: 17,
      name: 'Suzi Larson',
      age: 24,
      eligible: false,
    },
    {
      id: 18,
      name: 'Albina Mcconn',
      age: 21,
      eligible: true,
    },
    {
      id: 19,
      name: 'Brad Jansen',
      age: 47,
      eligible: true,
    },
    {
      id: 20,
      name: 'Elvira Selvy',
      age: 41,
      eligible: true,
    },
    {
      id: 21,
      name: 'Kitty Bollig',
      age: 31,
      eligible: false,
    },
    {
      id: 22,
      name: 'Edwin Peterson',
      age: 36,
      eligible: false,
    },
    {
      id: 23,
      name: 'Zetta Woodie',
      age: 32,
      eligible: true,
    },
    {
      id: 24,
      name: 'Santos Turnbull',
      age: 44,
      eligible: true,
    },
    {
      id: 25,
      name: 'Tifany Alberico',
      age: 20,
      eligible: false,
    },
    {
      id: 26,
      name: 'Emmett Andrade',
      age: 22,
      eligible: true,
    },
    {
      id: 27,
      name: 'Remedios Barfield',
      age: 29,
      eligible: false,
    },
    {
      id: 28,
      name: 'Waltraud Kuehn',
      age: 56,
      eligible: false,
    },
    {
      id: 29,
      name: 'Rosalba Allard',
      age: 57,
      eligible: true,
    },
    {
      id: 30,
      name: 'Cathrine Phifer',
      age: 36,
      eligible: true,
    },
    {
      id: 31,
      name: 'Ermelinda Whitlatch',
      age: 23,
      eligible: true,
    },
    {
      id: 32,
      name: 'Eilene Hail',
      age: 20,
      eligible: false,
    },
    {
      id: 33,
      name: 'Dusty Griffith',
      age: 19,
      eligible: true,
    },
    {
      id: 34,
      name: 'Ariane Sherrell',
      age: 62,
      eligible: false,
    },
    {
      id: 35,
      name: 'Arron Rowton',
      age: 54,
      eligible: false,
    },
    {
      id: 36,
      name: 'Mario Sherk',
      age: 33,
      eligible: true,
    },
    {
      id: 37,
      name: 'Marcos Turek',
      age: 23,
      eligible: false,
    },
    {
      id: 38,
      name: 'Tomi Mccune',
      age: 49,
      eligible: true,
    },
  ],
};

export default api;
